version: "3.5"

services:
  web:
    image: styliteag/nginx-docker-swarm:latest
    #entrypoint: ["/bin/sh", "-c", "echo START ; sleep 2073600"] # Enable if you yoe want to debug Start Problems
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - UPSTREAM=tasks.collabora
    networks:
      - traefik_public
      - default
    depends_on:
      - collabora
    # This is for docker-compose
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:collabora.your.domain
      - traefik.protocol=http
    deploy:
      replicas: 1
      # This is for docker stack
      labels:
        - traefik.enable=true
        - traefik.port=80
        - traefik.frontend.rule=Host:collabora.your.domain
        - traefik.protocol=http
        - traefik.frontend.passHostHeader=true
        - traefik.backend.loadbalancer.stickiness=true

  collabora:
    image: styliteag/collabora-code:latest
    #image: collabora/code
    env_file: ./collabora.env
    cap_add:
      - MKNOD
    deploy:
      replicas: 2
      #mode: global
      endpoint_mode: dnsrr # or vip
                           # But "tasks.<servicname>" always resolves to multiple A records
                           # vip resolves <servicenam> to a single record (The stack loadbalancer)
                           # dnsrr resolves <servicename> to multiple Records
      update_config:
        parallelism: 1
        delay: 120s

networks:
  traefik_public:
    external: true
